name: Through My Eyes
favicon: null
layout_spectrum: 1
typography_spectrum: 0.31146
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#a4a4a4'
    - '#d0d0d0'
    - '#181818'
    - '#646464'
  brandStrength: 0.7656412222422659
  lightness: 0.6518916883505881
  saturation: 0.1261123325675726
  rhythmicContrast: 0.38209507195279
purpose: []
