name: Through My Eyes
favicon: null
layout_spectrum: 0.74748
typography_spectrum: 0.31146
title: Through My Eyes
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#a4a4a4'
    - '#d0d0d0'
    - '#181818'
    - '#646464'
  brandStrength: 0.6875
  lightness: 0.875
  saturation: 0.75
  rhythmicContrast: 0.25
purpose: []
